### ISSUE TITLE
Request an Estimate button on Services page align

### ISSUE THREAD

**Issue by chrisdont** [alecluna/printworksapparel#142]
### What I'm trying to achieve

![image](https://user-images.githubusercontent.com/43280121/56944767-7f6fed80-6ad9-11e9-930c-0b7a4ca18815.png)

### Steps to reproduce the problem
1. 
2. 

### What I expected to happen
…

### Screenshots

**System information**
Operating system: 
Browser:

**Comment by christinetu** [comment]
Change to one button instead
